# Generated by Django 3.0.3 on 2020-10-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20201028_2328'), ('core', '0003_auto_20201028_2349'), ('core', '0004_auto_20201029_1223'), ('core', '0005_auto_20201029_1350'), ('core', '0006_auto_20201029_1354'), ('core', '0007_auto_20201029_1354'), ('core', '0008_auto_20201029_1355'), ('core', '0009_auto_20201029_1356'), ('core', '0010_auto_20201029_1356'), ('core', '0011_auto_20201029_1421'), ('core', '0012_auto_20201029_1422'), ('core', '0013_auto_20201029_1442')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.TextField()),
                ('comment_id', models.TextField()),
                ('reply_id', models.TextField()),
                ('profile_id', models.BigIntegerField()),
                ('user_name', models.TextField()),
                ('date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('likes', models.IntegerField()),
                ('user_id', models.TextField()),
                ('post_type', models.TextField()),
                ('row_id', models.TextField()),
                ('hate_speech', models.BooleanField()),
                ('page_name', models.TextField()),
                ('page_user_name', models.TextField()),
                ('page_likes_at_posting', models.TextField()),
                ('media_type', models.TextField()),
                ('post_likes', models.TextField()),
                ('comments', models.TextField()),
                ('shares', models.TextField()),
                ('angry_reactions', models.IntegerField()),
                ('media_link', models.TextField()),
                ('overperforming_score', models.FloatField()),
                ('hate_speech_item1', models.TextField()),
                ('hate_speech_item2', models.TextField()),
                ('hate_speech_item3', models.TextField()),
                ('hate_speech_item4', models.TextField()),
                ('targeted_group1', models.TextField()),
                ('targeted_group2', models.TextField()),
                ('targeted_group3', models.TextField()),
                ('targeted_group4', models.TextField()),
                ('election_topic_hs', models.BooleanField()),
                ('number_of_posts', models.IntegerField()),
                ('election_topic', models.BooleanField()),
                ('election_topic_keyword', models.BooleanField()),
                ('double_comment', models.BooleanField()),
            ],
        ),
    ]
