# Generated by Django 3.0.3 on 2020-10-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_malicioususers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malicioususers',
            name='hs_freq',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='malicioususers',
            name='malicious_score',
            field=models.IntegerField(db_index=True),
        ),
    ]
