# Generated by Django 3.0.3 on 2020-10-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201029_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malicioususers',
            name='hs_freq',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='malicioususers',
            name='malicious_score',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='malicioususers',
            index=models.Index(fields=['user_id', 'hs_freq', 'malicious_score'], name='core_malici_user_id_2c598a_idx'),
        ),
        migrations.AddIndex(
            model_name='malicioususers',
            index=models.Index(fields=['user_id'], name='user_id_idx'),
        ),
    ]
