# Generated by Django 3.0.3 on 2020-10-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201029_2148'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='malicioususers',
            index=models.Index(fields=['malicious_score'], name='malicious_score_idx'),
        ),
    ]
