# Generated by Django 3.0.3 on 2020-10-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201029_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawindow',
            name='election_topic_keyword',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='datawindow',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
