# Generated by Django 3.0.3 on 2020-10-29 23:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201029_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 1, 0, 0, tzinfo=utc))),
            ],
        ),
    ]
