# Generated by Django 3.0.3 on 2020-10-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wordcloud'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaliciousUsers',
            new_name='MaliciousUser',
        ),
        migrations.RemoveIndex(
            model_name='malicioususer',
            name='core_malici_user_id_2c598a_idx',
        ),
        migrations.AddIndex(
            model_name='malicioususer',
            index=models.Index(fields=['user_id', 'hs_freq', 'malicious_score'], name='core_malici_user_id_14bc8c_idx'),
        ),
    ]
