# Generated by Django 3.0.3 on 2020-10-31 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201029_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=6, max_digits=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 1, 0, 0, tzinfo=utc))),
            ],
        ),
    ]
