# Generated by Django 3.0.3 on 2020-10-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201029_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawindow',
            name='hate_speech',
            field=models.BooleanField(),
        ),
    ]
