# Generated by Django 3.0.3 on 2020-10-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201029_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawindow',
            name='number_of_posts',
            field=models.IntegerField(),
        ),
    ]
