# Generated by Django 3.0.3 on 2020-10-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201031_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawindow',
            name='profile_id',
            field=models.TextField(),
        ),
    ]
