# Generated by Django 3.0.3 on 2020-10-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201031_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawindow',
            name='page_likes_at_posting',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datawindow',
            name='profile_id',
            field=models.BigIntegerField(),
        ),
    ]
