# Generated by Django 3.0.3 on 2020-10-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201029_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawindow',
            name='angry_reactions',
            field=models.IntegerField(),
        ),
    ]
