# Generated by Django 3.0.3 on 2020-11-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201031_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawindow',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='datawindow',
            index=models.Index(fields=['user_id', 'targeted_group1', 'targeted_group2', 'targeted_group3', 'targeted_group4'], name='core_datawi_user_id_c93182_idx'),
        ),
        migrations.AddIndex(
            model_name='datawindow',
            index=models.Index(fields=['user_id'], name='core_datawi_user_id_3e439d_idx'),
        ),
    ]
