# Generated by Django 3.0.3 on 2020-11-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201103_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lexicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
                ('targetted_group', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
    ]
