# Generated by Django 3.0.3 on 2020-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201029_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawindow',
            name='profile_id',
            field=models.BigIntegerField(),
        ),
    ]
